import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Navbar from "./components/Navbar";
import BackgroundImage from "./components/BackgroundImage";
import backgroundmandala from "./public/backgroundmandala.jpg";
import "./styles/styles.css";
import "tailwindcss/tailwind.css";

const monsterrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {" "}
      <body className={`${monsterrat.className}`}>
        <BackgroundImage imageSrc={backgroundmandala}>
          <Navbar />
          {children}
        </BackgroundImage>
      </body>
    </html>
  );
}
