import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import "./globals.css";
import "tailwindcss/tailwind.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-l bg-violet-300">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
